build:
  image: node:latest
  stage: build
  only:
    - master
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  image: debian:stable
  stage: deploy
  only:
    - master
  dependencies:
    - build
  script:
    - echo "Generated bundles and assets to upload:"
    - cd dist && ls
    - echo "Running curl to upload files via FTP"
    - cd dist && curl -T * ftp://ci@bigtreeworld.com:0rthanc93@ftp.bigtreeworld.com


