build:
  image: node:latest
  stage: build
  only:
    - master
  before_script:
    - npm install
  script:
    - npm run build
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/

deploy:
  image: appropriate/curl:latest
  stage: deploy
  only:
    - master
  dependencies:
    - build
  script:
    - echo "Generated bundles and assets to upload:"
    - cd dist
    - ls
    - echo "Running curl to upload files via FTP"
    - curl -T * ftp://ci@bigtreeworld.com:0rthanc93@ftp.bigtreeworld.com


